# 3.18



#### wrapper class(包装类)

> 好像有一点是这个比正常的基本类型慢，但是为什么还是需要呢，因为他说在后面的API Framework 里面要用到，目前不是很清楚哈

```java
public class Count {
	public static void main(String[] args) {
		String str="123";
		int n=Integer.parseInt(str);
		System.out.println(n);
	}//里面必须是数字不然不行
}
//像这样可以转换

int i=5;
		Integer n = new Integer(i);
		int j=n.intValue();
		Integer value=i;
		int k=value;
		System.out.println(n);
```





#### final

* value
* method(感觉在inheritance中用到)
* class（不能extend）？有什么用呢







# interface

1. 与anonymous class 结合在一起
2. Type of interface
   1. Normal
   2. Single abstract method(functional interface)所以不算是default
   3. Marker interface 
3. 可以有default method 了（1.8以后）

```java
interface Demo{
	void adc();
	default void show() {//can be overrided
		System.out.println("in show");
	}
}
class DemoImp implements Demo{
	@Override
	public void adc() {
		System.out.println("in adc");
	}
	public void test() {
		System.out.println("In test");
	}
    //public void show(){
    //System.out.println("In new show");
//}
}
public class Count {
	public static void main(String[] args) {
		Demo obj=new DemoImp();
		obj.adc();
		obj.show();
//		obj.test();不行的，因为你有的是Demo的蓝图，只能输出demo中有的东西呵
	}
}
```

```java
interface Demo{
	void adc();
	default void show() {
		System.out.println("in show");
	}
}
interface MyDEMO{
	default void show() {
		System.out.println("I'm in mydemo");
	}
}
class DemoImp implements Demo,MyDEMO{

	@Override
	public void adc() {
		System.out.println("in adc");
	}
	public void test() {
		System.out.println("In test");
	}
	@Override
	public void show() {
		// TODO Auto-generated method stub
		MyDEMO.super.show();//如果出现了同样的method 你是可以选择call 哪个的，也可以两者都不要自己重写一个
	}
	
}
public class Count {
	public static void main(String[] args) {
		Demo obj=new DemoImp();
		obj.adc();
		obj.show();
//		obj.test();
	}
}
```

1. 这上面i关于interface 相撞的情况
2. interface里面还可以有static 是可以的，这样再去搞个class 啥的浪费
3. interface里面的int 啥的是`final`的



#### public default private protected**（访问控制权限）**

|                                | public | default | private | protected |
| ------------------------------ | :----: | :-----: | :-----: | :-------: |
| own package                    |   √    |    √    |         |     √     |
| all package                    |   √    |         |         |           |
| subclass/own class(own packge) |   √    |    √    |    √    |     √     |
| subclass(all package)          |   √    |         |         |     √     |



大概就是这样了<img src="C:\Users\zbr\AppData\Roaming\Typora\typora-user-images\image-20200318203334422.png" alt="image-20200318203334422" style="zoom: 33%;" />

<img src="C:\Users\zbr\AppData\Roaming\Typora\typora-user-images\image-20200318203432832.png" alt="image-20200318203432832" style="zoom: 33%;" />





#### 异常处理 Exception handling

这里体现了多态，而且基本上是父类 子类的关系，都有继承的，像一个思维导图一样

一般输出e的时候都是输出你对应的exception

* ##### try catch and finally

> 在这里面我还遇到了bufferreader 目前不知道什么东西 反正知道的是Scanner很像，不过他好像就只可以输进String 但是他好像还要closed  啥啊？

```java
public static void main(String[] args) {
		int i=2;
		int j=0;
		try {
			int m=i/j;//这里出现了error
		}
		catch(Exception e) {
			System.out.println("Error");
		}
		finally {
			System.out.println("bye");//这里的finally作用还没展现出来，后面再讲下
		}
	System.out.println("Execute");
	}
```

> 这个的作用是什么，当我们运行一个程序的时候，如果遇到不对的程序就直接运行不了是吧，那这个的作用呢，是看下try里面的东西能不能运行，如果不行的话被catch到这里去，不影响接下来的运行，他就是一步步来的把，try catch finally，finally不管你运不运行的了都finally这样子的。大概原理就是这样。

```java
public static void main(String[] args) {
		int i=2;
		int j=0;
		try {
			int m=i/j;
		}
		catch(ArithmeticException e) {
			System.out.println("Arith error");//这次多加了一个这个东西，是啥呢，代表错误的类型还有很多别的错误的，如果你去寻找源头去看的话，这是一个class extends Exception 说明Exception是总的，你这个必须写在Exception前面不然就没意义了
		}
		catch(Exception e) {
			System.out.println("Error");//而且一般都要写这个，如果你没写这个出现了一个不是Arith的错误的话，那照样程序崩溃的
		}
		finally {
			System.out.println("bye");
		}
	System.out.println("Execute");
	}
```

你看上面 catch也可以overload 但可以改成下面一种情况看个人需要

```java
catch(ArithmeticException | ArrayIndexOutOfBoundsException e){
    System.out.println("Error");
}
```

可以改成这样 但是有一个缺点是输出相同东西这个可能不是我们需要的

###### finally

这里体现了，如果try或catch有return指令，finally还是会执行，流程会跳到finally然后再回到return指令

#### checked and unchecked

现在个人片面的理解，其实是和runtime error 和compiletime error exception 可能好点？

<img src="C:\Users\zbr\AppData\Roaming\Typora\typora-user-images\image-20200319000407968.png" alt="image-20200319000407968" style="zoom:50%;" />

compiletime exception 的话就是可以checked的，当你在打出什么东西的时候会提醒你的错误，但也不一定是这个吧，比如说数组超过的时候就不会提醒你，反正提醒的是compiler可以发现的错误

runtime exception 是当你run了之后才会发现的错误，一些不寻常的错误 反正 比如不知道你电脑会死机 不知道你文件找不到了这样的错误



#### Throw and throws

实际上是抛出的意思，但我没那么了解，我了解区别但是不会用啊，

| THROW                                                | THROWS                                              |
| ---------------------------------------------------- | --------------------------------------------------- |
| deal with customized unchecked exception(checked ok) | deal with checked exception                         |
| 要和try catch 一起用吧，if sb throw 得有人能来catch  | 一般是当交接的时候这里可能有一个exception你要告诉他 |
| 只能throw一个抛出一个exception                       | 下面可能有多种类型的exception 可以多个              |
| 在method里面使用                                     | 在method外面使用                                    |

```java
public class Count {
		void m() throws IOException{
			throw new IOException("device error");
		}
		void n() throws IOException{
			m();
		}
		void p() {
			try {
				n();
			}
			catch(Exception e) {
				System.out.println("exception handled");
			}
		}
		public static void main(String[] args){
			Count c= new Count();
			c.p();
			System.out.println("nomal");
	}
	}
//exception handled
//nomal

```

感觉好像可以理解了，太艰难了

你也可以自己定义一个exception，不过好像要用到super什么东西，还不是很会，下午去试一下，

```java
//public class ZeroException extends Exception{
//	int age=10;
//	public void display(){
//		if(age>5) {
//			throw new ArithmeticException();
//		}
//	}
//	public ZeroException() {
//		
//	}
```

![image-20200319104608633](C:\Users\zbr\AppData\Roaming\Typora\typora-user-images\image-20200319104608633.png)

![image-20200319104618631](C:\Users\zbr\AppData\Roaming\Typora\typora-user-images\image-20200319104618631.png)

![image-20200319104626994](C:\Users\zbr\AppData\Roaming\Typora\typora-user-images\image-20200319104626994.png)

<img src="C:\Users\zbr\AppData\Roaming\Typora\typora-user-images\image-20200319104638430.png" alt="image-20200319104638430" style="zoom:50%;" />

![image-20200319104650559](C:\Users\zbr\AppData\Roaming\Typora\typora-user-images\image-20200319104650559.png)

##### 终总结：

关于overload的catch一定从小到大 不然就没用了哈，大概就先这样了后面贴一些图上来

![image-20200320204126572](C:\Users\zbr\AppData\Roaming\Typora\typora-user-images\image-20200320204126572.png)